#!/bin/zsh
curl -o Alaska-Colleges.html http://localhost:3000/college-state/Alaska
curl -o Alabama-Colleges.html http://localhost:3000/college-state/Alabama
curl -o Arkansas-Colleges.html http://localhost:3000/college-state/Arkansas
curl -o Arizona-Colleges.html http://localhost:3000/college-state/Arizona
curl -o California-Colleges.html http://localhost:3000/college-state/California
curl -o Colorado-Colleges.html http://localhost:3000/college-state/Colorado
curl -o Connecticut-Colleges.html http://localhost:3000/college-state/Connecticut
curl -o District-of-Columbia-Colleges.html http://localhost:3000/college-state/District%20of%20Columbia
curl -o Delaware-Colleges.html http://localhost:3000/college-state/Delaware
curl -o Florida-Colleges.html http://localhost:3000/college-state/Florida
curl -o Georgia-Colleges.html http://localhost:3000/college-state/Georgia
curl -o Hawaii-Colleges.html http://localhost:3000/college-state/Hawaii
curl -o Iowa-Colleges.html http://localhost:3000/college-state/Iowa
curl -o Idaho-Colleges.html http://localhost:3000/college-state/Idaho
curl -o Illinois-Colleges.html http://localhost:3000/college-state/Illinois
curl -o Indiana-Colleges.html http://localhost:3000/college-state/Indiana
curl -o Kansas-Colleges.html http://localhost:3000/college-state/Kansas
curl -o Kentucky-Colleges.html http://localhost:3000/college-state/Kentucky
curl -o Louisiana-Colleges.html http://localhost:3000/college-state/Louisiana
curl -o Massachusetts-Colleges.html http://localhost:3000/college-state/Massachusetts
curl -o Maryland-Colleges.html http://localhost:3000/college-state/Maryland
curl -o Maine-Colleges.html http://localhost:3000/college-state/Maine
curl -o Michigan-Colleges.html http://localhost:3000/college-state/Michigan
curl -o Minnesota-Colleges.html http://localhost:3000/college-state/Minnesota
curl -o Missouri-Colleges.html http://localhost:3000/college-state/Missouri
curl -o Mississippi-Colleges.html http://localhost:3000/college-state/Mississippi
curl -o Montana-Colleges.html http://localhost:3000/college-state/Montana
curl -o North-Carolina-Colleges.html http://localhost:3000/college-state/North%20Carolina
curl -o North-Dakota-Colleges.html http://localhost:3000/college-state/North%20Dakota
curl -o Nebraska-Colleges.html http://localhost:3000/college-state/Nebraska
curl -o New-Hampshire-Colleges.html http://localhost:3000/college-state/New%20Hampshire
curl -o New-Jersey-Colleges.html http://localhost:3000/college-state/New%20Jersey
curl -o New-Mexico-Colleges.html http://localhost:3000/college-state/New%20Mexico
curl -o Nevada-Colleges.html http://localhost:3000/college-state/Nevada
curl -o New-York-Colleges.html http://localhost:3000/college-state/New%20York
curl -o Ohio-Colleges.html http://localhost:3000/college-state/Ohio
curl -o Oklahoma-Colleges.html http://localhost:3000/college-state/Oklahoma
curl -o Oregon-Colleges.html http://localhost:3000/college-state/Oregon
curl -o Pennsylvania-Colleges.html http://localhost:3000/college-state/Pennsylvania
curl -o Puerto-Rico-Colleges.html http://localhost:3000/college-state/Puerto%20Rico
curl -o Rhode-Island-Colleges.html http://localhost:3000/college-state/Rhode%20Island
curl -o South-Carolina-Colleges.html http://localhost:3000/college-state/South%20Carolina
curl -o South-Dakota-Colleges.html http://localhost:3000/college-state/South%20Dakota
curl -o Tennessee-Colleges.html http://localhost:3000/college-state/Tennessee
curl -o Texas-Colleges.html http://localhost:3000/college-state/Texas
curl -o Utah-Colleges.html http://localhost:3000/college-state/Utah
curl -o Virginia-Colleges.html http://localhost:3000/college-state/Virginia
curl -o Virgin-Islands-Colleges.html http://localhost:3000/college-state/Virgin%20Islands
curl -o Vermont-Colleges.html http://localhost:3000/college-state/Vermont
curl -o Washington-Colleges.html http://localhost:3000/college-state/Washington
curl -o Wisconsin-Colleges.html http://localhost:3000/college-state/Wisconsin
curl -o West Virginia-Colleges.html http://localhost:3000/college-state/West%20Virginia
curl -o Wyoming-Colleges.html http://localhost:3000/college-state/Wyoming