#!/bin/zsh
curl -o Alaska-Trade-Schools.html http://localhost:3000/trade-school-state/Alaska
curl -o Alabama-Trade-Schools.html http://localhost:3000/trade-school-state/Alabama
curl -o Arkansas-Trade-Schools.html http://localhost:3000/trade-school-state/Arkansas
curl -o Arizona-Trade-Schools.html http://localhost:3000/trade-school-state/Arizona
curl -o California-Trade-Schools.html http://localhost:3000/trade-school-state/California
curl -o Colorado-Trade-Schools.html http://localhost:3000/trade-school-state/Colorado
curl -o Connecticut-Trade-Schools.html http://localhost:3000/trade-school-state/Connecticut
curl -o District-of-Columbia-Trade-Schools.html http://localhost:3000/trade-school-state/District%20of%20Columbia
curl -o Delaware-Trade-Schools.html http://localhost:3000/trade-school-state/Delaware
curl -o Florida-Trade-Schools.html http://localhost:3000/trade-school-state/Florida
curl -o Georgia-Trade-Schools.html http://localhost:3000/trade-school-state/Georgia
curl -o Hawaii-Trade-Schools.html http://localhost:3000/trade-school-state/Hawaii
curl -o Iowa-Trade-Schools.html http://localhost:3000/trade-school-state/Iowa
curl -o Idaho-Trade-Schools.html http://localhost:3000/trade-school-state/Idaho
curl -o Illinois-Trade-Schools.html http://localhost:3000/trade-school-state/Illinois
curl -o Indiana-Trade-Schools.html http://localhost:3000/trade-school-state/Indiana
curl -o Kansas-Trade-Schools.html http://localhost:3000/trade-school-state/Kansas
curl -o Kentucky-Trade-Schools.html http://localhost:3000/trade-school-state/Kentucky
curl -o Louisiana-Trade-Schools.html http://localhost:3000/trade-school-state/Louisiana
curl -o Massachusetts-Trade-Schools.html http://localhost:3000/trade-school-state/Massachusetts
curl -o Maryland-Trade-Schools.html http://localhost:3000/trade-school-state/Maryland
curl -o Maine-Trade-Schools.html http://localhost:3000/trade-school-state/Maine
curl -o Michigan-Trade-Schools.html http://localhost:3000/trade-school-state/Michigan
curl -o Minnesota-Trade-Schools.html http://localhost:3000/trade-school-state/Minnesota
curl -o Missouri-Trade-Schools.html http://localhost:3000/trade-school-state/Missouri
curl -o Mississippi-Trade-Schools.html http://localhost:3000/trade-school-state/Mississippi
curl -o Montana-Trade-Schools.html http://localhost:3000/trade-school-state/Montana
curl -o North-Carolina-Trade-Schools.html http://localhost:3000/trade-school-state/North%20Carolina
curl -o North-Dakota-Trade-Schools.html http://localhost:3000/trade-school-state/North%20Dakota
curl -o Nebraska-Trade-Schools.html http://localhost:3000/trade-school-state/Nebraska
curl -o New-Hampshire-Trade-Schools.html http://localhost:3000/trade-school-state/New%20Hampshire
curl -o New-Jersey-Trade-Schools.html http://localhost:3000/trade-school-state/New%20Jersey
curl -o New-Mexico-Trade-Schools.html http://localhost:3000/trade-school-state/New%20Mexico
curl -o Nevada-Trade-Schools.html http://localhost:3000/trade-school-state/Nevada
curl -o New-York-Trade-Schools.html http://localhost:3000/trade-school-state/New%20York
curl -o Ohio-Trade-Schools.html http://localhost:3000/trade-school-state/Ohio
curl -o Oklahoma-Trade-Schools.html http://localhost:3000/trade-school-state/Oklahoma
curl -o Oregon-Trade-Schools.html http://localhost:3000/trade-school-state/Oregon
curl -o Pennsylvania-Trade-Schools.html http://localhost:3000/trade-school-state/Pennsylvania
curl -o Puerto-Rico-Trade-Schools.html http://localhost:3000/trade-school-state/Puerto%20Rico
curl -o Rhode-Island-Trade-Schools.html http://localhost:3000/trade-school-state/Rhode%20Island
curl -o South-Carolina-Trade-Schools.html http://localhost:3000/trade-school-state/South%20Carolina
curl -o South-Dakota-Trade-Schools.html http://localhost:3000/trade-school-state/South%20Dakota
curl -o Tennessee-Trade-Schools.html http://localhost:3000/trade-school-state/Tennessee
curl -o Texas-Trade-Schools.html http://localhost:3000/trade-school-state/Texas
curl -o Utah-Trade-Schools.html http://localhost:3000/trade-school-state/Utah
curl -o Virginia-Trade-Schools.html http://localhost:3000/trade-school-state/Virginia
curl -o Virgin-Islands-Trade-Schools.html http://localhost:3000/trade-school-state/Virgin%20Islands
curl -o Vermont-Trade-Schools.html http://localhost:3000/trade-school-state/Vermont
curl -o Washington-Trade-Schools.html http://localhost:3000/trade-school-state/Washington
curl -o Wisconsin-Trade-Schools.html http://localhost:3000/trade-school-state/Wisconsin
curl -o West-Virginia-Trade-Schools.html http://localhost:3000/trade-school-state/West%20Virginia
curl -o Wyoming-Trade-Schools.html http://localhost:3000/trade-school-state/Wyoming