#!/bin/zsh
curl -o Alabama-Scholarships.html http://localhost:3000/state-scholarships/Alabama;
curl -o Alaska-Scholarships.html http://localhost:3000/state-scholarships/Alaska;
curl -o Arizona-Scholarships.html http://localhost:3000/state-scholarships/Arizona;
curl -o Arkansas-Scholarships.html http://localhost:3000/state-scholarships/Arkansas;
curl -o California-Scholarships.html http://localhost:3000/state-scholarships/California;
curl -o Colorado-Scholarships.html http://localhost:3000/state-scholarships/Colorado;
curl -o Connecticut-Scholarships.html http://localhost:3000/state-scholarships/Connecticut;
curl -o DC-Scholarships.html http://localhost:3000/state-scholarships/DC;
curl -o Delaware-Scholarships.html http://localhost:3000/state-scholarships/Delaware;
curl -o Florida-Scholarships.html http://localhost:3000/state-scholarships/Florida;
curl -o Georgia-Scholarships.html http://localhost:3000/state-scholarships/Georgia;
curl -o Hawaii-Scholarships.html http://localhost:3000/state-scholarships/Hawaii;
curl -o Idaho-Scholarships.html http://localhost:3000/state-scholarships/Idaho;
curl -o Illinois-Scholarships.html http://localhost:3000/state-scholarships/Illinois;
curl -o Indiana-Scholarships.html http://localhost:3000/state-scholarships/Indiana;
curl -o Iowa-Scholarships.html http://localhost:3000/state-scholarships/Iowa;
curl -o Kansas-Scholarships.html http://localhost:3000/state-scholarships/Kansas;
curl -o Kentucky-Scholarships.html http://localhost:3000/state-scholarships/Kentucky;
curl -o Louisiana-Scholarships.html http://localhost:3000/state-scholarships/Louisiana;
curl -o Maine-Scholarships.html http://localhost:3000/state-scholarships/Maine;
curl -o Maryland-Scholarships.html http://localhost:3000/state-scholarships/Maryland;
curl -o Massachusetts-Scholarships.html http://localhost:3000/state-scholarships/Massachusetts;
curl -o Michigan-Scholarships.html http://localhost:3000/state-scholarships/Michigan;
curl -o Minnesota-Scholarships.html http://localhost:3000/state-scholarships/Minnesota;
curl -o Mississippi-Scholarships.html http://localhost:3000/state-scholarships/Mississippi;
curl -o Missouri-Scholarships.html http://localhost:3000/state-scholarships/Missouri;
curl -o Montana-Scholarships.html http://localhost:3000/state-scholarships/Montana;
curl -o Nebraska-Scholarships.html http://localhost:3000/state-scholarships/Nebraska;
curl -o Nevada-Scholarships.html http://localhost:3000/state-scholarships/Nevada;
curl -o New-Hampshire-Scholarships.html http://localhost:3000/state-scholarships/New Hampshire;
curl -o New-Jersey-Scholarships.html http://localhost:3000/state-scholarships/New Jersey;
curl -o New-Mexico-Scholarships.html http://localhost:3000/state-scholarships/New Mexico;
curl -o New-York-Scholarships.html http://localhost:3000/state-scholarships/New York;
curl -o North-Carolina-Scholarships.html http://localhost:3000/state-scholarships/North Carolina;
curl -o North-Dakota-Scholarships.html http://localhost:3000/state-scholarships/North Dakota;
curl -o Ohio-Scholarships.html http://localhost:3000/state-scholarships/Ohio;
curl -o Oklahoma-Scholarships.html http://localhost:3000/state-scholarships/Oklahoma;
curl -o Oregon-Scholarships.html http://localhost:3000/state-scholarships/Oregon;
curl -o Pennsylvania-Scholarships.html http://localhost:3000/state-scholarships/Pennsylvania;
curl -o Puerto-Rico-Scholarships.html http://localhost:3000/state-scholarships/Puerto Rico;
curl -o Rhode-Island-Scholarships.html http://localhost:3000/state-scholarships/Rhode Island;
curl -o South-Carolina-Scholarships.html http://localhost:3000/state-scholarships/South Carolina;
curl -o South-Dakota-Scholarships.html http://localhost:3000/state-scholarships/South Dakota;
curl -o Tennessee-Scholarships.html http://localhost:3000/state-scholarships/Tennessee;
curl -o Texas-Scholarships.html http://localhost:3000/state-scholarships/Texas;
curl -o Utah-Scholarships.html http://localhost:3000/state-scholarships/Utah;
curl -o Vermont-Scholarships.html http://localhost:3000/state-scholarships/Vermont;
curl -o Virginia-Scholarships.html http://localhost:3000/state-scholarships/Virginia;
curl -o Washington-Scholarships.html http://localhost:3000/state-scholarships/Washington;
curl -o West-Virginia-Scholarships.html http://localhost:3000/state-scholarships/West Virginia;
curl -o Wisconsin-Scholarships.html http://localhost:3000/state-scholarships/Wisconsin;
curl -o Wyoming-Scholarships.html http://localhost:3000/state-scholarships/Wyoming;